################################################################
#                        MineBBSTopper                         #
#                    未经允许禁止转载/倒卖/发布                    #
#                        作者: 404Yuner                        #
#                       交流群：301662621                       #
################################################################
# GitHub：https://github.com/404Yuner/MineBBSTopper
# MineBBS：https://www.minebbs.com/resources/minebbstopper-gui-99.8762/

# 请勿更改版本！！！！
Version: 2.0
# 是否开启更新检测 - 建议开启，插件需要您的反馈
UpdateCheck: true

# 数据储存类型
Database:
  # 可选类型 SQLite / MySQL / Yaml   三种其中之一就行，可忽略大小写
  # 如果你用 JAVA8 或 MySQL 5.x ，那有一定的几率连不上MySQL，届时还请使用SQLite或Yaml
  # 虽然SQLite和Yaml都是本地储存，但是SQLite读取更快。如果选择SQLite报错，则请使用Yaml
  type: 'Yaml'
  # 选择MySQL后必填
  MySQL:
    host: localhost
    port: 3306
    user: root
    database: mysql
    password: password
    # 下面的选项，请勿更改！
    # 如果你知道你在做什么
    useSSL: false
    maximumPoolSize: 5
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000

# PAPI 支持 需要前置插件PlaceholderAPI
# 全局类型变量：
#  %minebbstopper_global_cantop% 返回是否可顶贴的布尔值(不含时间段情况)
#  %minebbstopper_global_count% 返回服务器总的顶贴次数
#  %minebbstopper_global_cooldown_<格式类型:iso或long>% 返回其中一种全局冷却时间的格式
#  %minebbstopper_global_rank_<任意整数位次>% 返回顶贴排行榜上指定位次的排名情况
#  %minebbstopper_global_serverurl% 返回填写宣传页面完整的地址
#  %minebbstopper_global_techurl% 返回填写教程页面完整的地址
# 玩家类型变量：
#  %minebbstopper_player_count% 返回玩家总的顶贴次数
#  %minebbstopper_player_todaycount% 返回玩家当日的顶贴次数
#  %minebbstopper_player_lasttime% 返回玩家上次顶贴的时间
#  %minebbstopper_player_countother_<玩家名>% 返回指定玩家总的顶贴次数
#  %minebbstopper_player_reward_<奖励id>% 返回玩家此奖励状态的布尔值

Setting:
  # 填写宣传页面完整的地址。
  # ===========================================================
  # 顶贴的原理是获取网页上顶贴时间的时间戳，而非调用MINEBBS的接口
  # 请在插件启动时检查你所配置的网页是否能被插件获取到顶贴时间
  # 如果获取不到，意味着你的上一次顶贴距今已经很久了，请重新顶贴后再试
  # ===========================================================
  # 特别提示：插件无法获取是谁顶贴，所以请提醒玩家在顶贴后的第一时间去游戏内领取奖励
  # ===========================================================
  serverUrl: 'https://www.minebbs.com/threads/luxuria-1-21-x-rpg.28022/'
  # 当玩家顶贴后，可领取奖励的限定时间范围。单位 分
  claimTime: 10
  # 成功顶贴后,下一次可领取奖励的冷却时间。单位 秒
  cooldown: 3600
  # 因网络波动设置的最大重连次数和重连间隔，如果超过最大重连次数，则禁用插件。
  # 设置格式为 最大重连次数:重连间隔秒数
  reconnect: '10:5'
  # 玩家顶贴领取奖励的时间段。单位 小时
  # 时间以符号-隔开。不支持具体到几分几秒
  claimSpan: '6-24'
  # 菜单打开间隔。防止玩家频繁打开菜单引起的资源占用。单位 秒
  openInterval: 0.5
  # 玩家点击菜单间隔，防止玩家通过连点器刷取奖励。单位 秒
  clickInterval: 0.5
  # 排行榜缓存刷新间隔，避免频繁操作数据库。单位 秒
  rankRefreshInterval: 1800
  # 教程网址填写处，留空不显示
  techUrl: '暂未配置教程网站'
  # 显示在排行榜上的玩家数量。默认显示前十名
  rankPlayer: 10
  # 进服时，是否给从来没有顶贴过的玩家发送提示？
  sendRemindMessage: true
  # 代理的配置
  proxy:
    # 是否启用代理？不知道什么是代理的别开
    enable: false
    # 代理IP
    ip: '127.0.0.1'
    # 代理端口
    port: 10809

# ===============================================================
# 支持的动作组
# 支持自动解析PlaceholderAPI占位符 ；如果没有安装，则解析%player%为玩家名
# 游戏内可使用 /minebbstopper test normal/offday 测试奖励发放
# ***************************************************************
# 获得该奖项后执行的动作类型，不写动作类型默认为玩家执行
# [console]give %player_name% diamond -> 以控制台身份执行指令
# [player]minebbstopper open -> 以玩家身份执行指令
# [op]kit new -> 以op身份执行指令。不建议使用！原理是给予op，执行指令后撤销op。若是以后出现问题别怪我没提醒过你！
# [tell]你的内容\n换行下一行内容 -> 向玩家发送消息，可使用\n可换行
# [broadcast]你的内容 -> 向全体玩家发送广播消息。若开启BC，则自动会将广播消息发送至所有子服（前提需安装本插件）
# [delay]10 -> 对后面的操作进行延迟操作。单位：秒
# [give-money]100.55 -> 给予玩家金币数量。或随机值配置：100.55-200.55
# [give-points]10 -> 给予玩家点券数量。只能接着整数值，否则发放失败！！！或随机值配置：100-200   <PlayerPoints 3.x版本专属>
# [title]主标题内容 副标题内容 进入时间 停留时间 淡出时间 -> 给玩家发送标题，空格分割参数。时间单位：tick
# [bossbar]内容 颜色 持续时间 -> 给玩家展示BOSSBAR。颜色可选值为：PINK,BLUE,RED,GREEN,YELLOW,PURPLE,WHITE；时间单位：秒
# [connect]xx服务器 -> 让玩家连接xx服务器，BC专属
# [sound]xxx -> 查看可用音效：https://pastebin.com/EfQKLUuN
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 领取时执行的动作组，可配置领取条件。
# 支持6种条件运算符：> < >= <= != ==
# 自动解析PlaceholderAPI占位符进行比较
# 如果匹配，则执行对应的动作。不匹配，则不执行。
# ***************************************************************
#
# @condition: 内容 运算符 内容       这里空格不敏感
#
# [tell]测试的数字大于等于100@condition:%player_level% >= %player_level%
# [tell]测试的数字小于100@condition:%player_level% < 100
# [tell]测试的数字等于100@condition:%player_level% == 100
# [tell]测试的字符串相等@condition:%player_name% == TEST_NAME
# [tell]测试的字符串不相等@condition:%player% != TEST_NAME
# [tell]玩家有minebbstopper.test权限@condition:%player_has_permission_minebbstopper.test% == yes
# =================================================================
Rewards:
  # 限制玩家当日能顶贴的次数
  limit:
    # 是否启用
    enable: false
    # 一天能领取几次顶帖奖励
    times: 3

  # 普通顶贴一次的奖励
  normal:
    commands:
      - '[broadcast]&6玩家 &a%player% &6刚刚完成了顶贴,获得了丰厚奖励,大家也来试试吧!\n&c详情指令: /minebbstopper open'
      - '[console]give %player% diamond 10'
      - '[title]&a感谢支持！ &b奖励已发放！ 20 60 20'
      # - '[tell]这个是给有vip权限的人的奖励@condition:%player_has_permission_vip% == yes'
      # - '[tell]这个是给svip会员的奖励@condition:%luckperms_highest_group_by_weight% == svip' # <-需安装luckperm扩展
      # - '[give-money]500-1000' # -> 随机金币
      # - '[give-points]50-100' # -> 随机点券

  # 配置特定日期内顶贴的专属奖励
  offday:
    # 是否启用
    enable: false
    # 是否为额外奖励 (是否还会给与普通的奖励)
    extra: true
    # 哪些日期会应用于这项设置
    # 表示一个星期中的某一天: SUNDAY(周日), MONDAY(周一), TUESDAY(周二)
    # WEDNESDAY(周三), THURSDAY(周四), FRIDAY(周五), SATURDAY(周六)
    # 普通日期格式为MM-dd, 例如10-01表示十月一日
    days:
      - 'SATURDAY'
      - 'SUNDAY'
      - '10-01'
      - '05-01'
    # 领取时执行的动作组
    # 同样支持条件运算
    commands:
      - '[tell]&6这是休息日的奖励配置'

  # 激励奖励
  # 当玩家在无人顶贴超过一定时间之后顶贴, 这些奖励命令会被执行
  incentive:
    # 是否启用
    enable: false
    # 间隔时间, 单位为分钟
    # 距离上一次有人顶贴多久之后会给与激励奖励
    period: 30
    # 领取时执行的动作组
    # 同样支持条件运算
    commands:
      - '[tell]&6这是顶贴激励的奖励配置'
